docs/Test-Article.md

Testing pull requests from Stoplight branches.

Added docs/Test-Article.md

---

docs/API gateway changes/API-gateway-changes.md
docs/API gateway changes/JSON-and-XML-headers.md
docs/API gateway changes/New-API-url.md
docs/API gateway changes/Sending-API-key.md
docs/Conventions/Conventions.md
docs/Conventions/HTTP-response-codes.md
docs/Conventions/Pagination.md
docs/Conventions/RESTful-architecture.md
docs/Conventions/Retrieving-objects.md
docs/Getting started/API-best-practices.md
docs/Getting started/API-rate-limits.md
docs/Getting started/About-the-Whispir-platform-API.md
docs/Getting started/Auto-extension-of-daily-limits.md
docs/Getting started/Connect-to-the-API.md
docs/Getting started/Register-with-Whispir.md
docs/Getting started/Sending-messages.md
docs/Getting started/Whispir-API-Postman-Collection.md
toc.json

This branch contains the conceptual documentation from our old API docs authored in MD, as well as a the TOC json file which is needed to render the content properly with the sidebar.

Import of conceptual docs and TOC

---

openapi.yaml

Live Demo: https://developers.whispirdev.com/branches/wft-187-users-endpoint/b3A6MjAxMTEz-create-a-user
- Copy some attributes from contacts model
- Add shared response for users endpoint
- Add examples for each users attribute

Wft 187 Update Users endpoint

---

.spectral.yaml
openapi.yaml

- Add content-type and accept request headers
- update read/write template attributes
- update create template example

Enhance template endpoint docs

---

openapi.yaml

- Created callbackInstance model
- Created callbackInstance response object referring to schema
- Added GET endpoints for callbacks/{callbackId}/calls
- Added PUT endpoints for callbacks/{callbackId}/calls - to update the callback status only

Callback calls

---

.spectral.yaml
openapi.yaml

- Add request headers style guide
- Refine response headers style guide to remove Content-Type requirement for 204 responses
- Update all path request headers to use references

Add request headers style guide

---

.spectral.yaml
openapi.yaml

https://whispir.atlassian.net/browse/WFT-190
https://developers.whispirdev.com/branches/WFT-190-contacts-openapi-uplift/b3A6Mzg5NDM5NDk-create-a-contact

Contacts OpenAPI Spec Uplift

---

.spectral.yaml
openapi.yaml

* Add Spectral rule to enforce list-resource endpoints have pagination query parameters
* Add pagination query parameters to all list-resource endpoints

Paginated endpoints

---

.github/workflows/spectral.yml
.spectral.base.yaml
.spectral.yaml
openapi.yaml

- Add `Dynamic Distribution List` model
- Make request and response for distribution list endpoints be `oneOf` `Static` or `Dynamic` DLs

WFT-194 distribution list uplift

---

.spectral.yaml
openapi.yaml

Changes for the OpenAPI Spec uplift - Scenarios

Scenario uplift

---

.spectral.yaml
openapi.yaml

Uplifted events endpoint spec
- updated base event schema model
- added new Event response object
- added new Events response object 
- added /put event endpoint to update event
- Updated create event endpoint to include more explicit information

Events spec uplift

---

openapi.yaml

Updated section that describes the push message schema with:
- updated push message example
- added attributes and descriptions for the rich push attributes
- marked appId as required

Rich push options

---

.github/workflows/node-sdk.yml

- feat: add Cross Repo PR and Code Generation for OpenAPI

Add SDK Code Generation Github Workflow to OpenAPI Repository

---

.github/workflows/node-sdk.yml

fix: fix error for changelog commit

Bugfix: Remove Typo Error on node-sdk.yml

---

whispir-sdk-codegen/openapitools.json

Hi guys,
I have added some changes to `java` open API SDK codegen configuration file to be more explicit in defining the `additionalProperties` so that it fits the requirements for publishing to Maven Central Repositories found here:
https://central.sonatype.org/publish/requirements/

updated configuration file for java sdk generation

---

docs/Getting started/Authentication.md

Remove legacy API authentication query parameter documentation.

Remove legacy API query parameter reference

---

.github/workflows/conventional-commit.yml

feat: add conventional commit action

feat: add conventional commit action

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTING.md
LICENSE

- Issue templates
- Contribution guidelines

feat: added contribution guidelines and issue templates

---

.github/workflows/java-sdk.yml
.github/workflows/node-sdk.yml

* Use release trigger for creating Node SDK PR
* Use release tag for created PR branch

fix: use release trigger for sdk PRs

---

.github/workflows/generate-java-sdk.yml
.github/workflows/generate-node-sdk.yml

Fixes for Opening PR for whispir-node and whispir-java

fix: updated generate node and java sdk workflows

---

openapi.yaml

- Remove defaults from workspace name, start time and end time

fix: remove defaults from getActivities operation

---

docs/Getting started/JSON-and-XML-headers.md
openapi.yaml

* Specify readonly on all relevant attributes

fix: Specify readonly attributes

---

codegen/mustache/node/api-single.mustache
codegen/mustache/node/model.mustache

* Update mustache model templates to emit write-only types
* Update api mustache templates to consume write-only types

build(node): Generate and consume write-only models in node sdk

---

codegen/mustache/node/model.mustache

* Fix generation of nested array models

fix(node): Fix nested array model reference

---

openapi.yaml

* Merge dynamic and static DistributionList schemas

refactor: Merge dynamic and static DistributionList schemas

---

codegen/mustache/java/api.mustache
codegen/mustache/java/libraries/okhttp-gson/oneof_model.mustache
codegen/mustache/java/pojo.mustache

This adds `lastResponse` property to the models

feat: added lastResponse field to Models

---

codegen/mustache/java/api.mustache
codegen/mustache/java/libraries/okhttp-gson/oneof_model.mustache
codegen/mustache/java/pojo.mustache

* Add docId extractor for POST methods
* Remove redundant GSON methods that were polluting model namespace
* Remove commented JSON validation methods in models

build(java): Add docId extractor for POST methods

---

codegen/config/java.yml

fix(java): Fix config typo

---

openapi.yaml

* removed `enabled` attribute
* added `secret` attribute
* removed `userId`, `clientId`, `accountId`
* modified `type` to only contain option `basic`

chore: update Keys resource docs

---

toc.json

Committed by Whispir-Softwares on behalf of srapales@whispir.com
- Update the nav file to show the SSL/TLS doc

feat(SEC-1060): update getting started links
